name: chatterly
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.9.1
  pinput: ^2.2.31
  google_fonts: ^5.1.0
  country_code_picker: ^3.0.0
  country_picker: ^2.0.21
  flutter_riverpod: ^2.0.0-dev.9
  image_picker: ^0.8.5+3
  flutter_contacts: ^1.1.5
  uuid: ^3.0.6
  intl: ^0.17.0
  cached_network_image: ^3.2.1

  emoji_picker_flutter: ^1.3.0
  enough_giphy_flutter: ^0.3.0
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^9.2.0

  google_sign_in: ^6.1.0
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.0
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: 13.0.0
  photo_view: 0.14.0
  provider: ^6.0.1


  swipe_to: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
    android: "ic_launcher"
    image_path: "images/ic_launcher.png"
    min_sdk_android: 21 # android min sdk min:16, default 21





flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
